# Generated by Django 5.0 on 2025-06-25 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Kadry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fio", models.CharField(max_length=255, verbose_name="ФИО")),
                ("razryad", models.CharField(max_length=50, verbose_name="Разряд")),
                ("pasport", models.CharField(max_length=100, verbose_name="Паспорт")),
                ("telefon", models.CharField(max_length=20, verbose_name="Телефон")),
            ],
            options={
                "verbose_name": "Кадр",
                "verbose_name_plural": "Кадры",
                "db_table": "kadry",
            },
        ),
        migrations.CreateModel(
            name="KategoriyaResursa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nazvanie", models.CharField(max_length=255, verbose_name="Название")),
            ],
            options={
                "verbose_name": "Категория ресурса",
                "verbose_name_plural": "Категории ресурсов",
                "db_table": "kategoriya_resursa",
            },
        ),
        migrations.CreateModel(
            name="Specialnost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nazvanie",
                    models.CharField(
                        max_length=255, verbose_name="Название специальности"
                    ),
                ),
            ],
            options={
                "verbose_name": "Специальность",
                "verbose_name_plural": "Специальности",
            },
        ),
        migrations.CreateModel(
            name="Objekt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nazvanie", models.CharField(max_length=255, verbose_name="Название")),
                ("data_nachala", models.DateField(verbose_name="Дата начала")),
                (
                    "data_plan_zaversheniya",
                    models.DateField(verbose_name="Дата план завершения"),
                ),
                (
                    "data_fakt_zaversheniya",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата факт завершения"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("планируется", "Планируется"),
                            ("в работе", "В работе"),
                            ("завершён", "Завершён"),
                        ],
                        default="планируется",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "otvetstvennyj",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="object.kadry",
                        verbose_name="Ответственный",
                    ),
                ),
            ],
            options={
                "verbose_name": "Объект",
                "verbose_name_plural": "Объекты",
                "db_table": "objekt",
            },
        ),
        migrations.CreateModel(
            name="Resurs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "naimenovanie",
                    models.CharField(max_length=255, verbose_name="Наименование"),
                ),
                (
                    "edinica_izmereniya",
                    models.CharField(max_length=50, verbose_name="Единица измерения"),
                ),
                (
                    "kategoriya_resursa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="object.kategoriyaresursa",
                        verbose_name="Категория ресурса",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ресурс",
                "verbose_name_plural": "Ресурсы",
                "db_table": "resurs",
            },
        ),
        migrations.CreateModel(
            name="ResursyPoObjektu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kolichestvo",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Количество"
                    ),
                ),
                (
                    "cena",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Цена"
                    ),
                ),
                (
                    "tip",
                    models.CharField(
                        choices=[("план", "План"), ("факт", "Факт")],
                        max_length=10,
                        verbose_name="Тип",
                    ),
                ),
                (
                    "objekt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="object.objekt",
                        verbose_name="Объект",
                    ),
                ),
                (
                    "resurs",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="object.resurs",
                        verbose_name="Ресурс",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ресурсы по объекту",
                "verbose_name_plural": "Ресурсы по объектам",
                "db_table": "resursy_po_objektu",
            },
        ),
        migrations.AddField(
            model_name="kadry",
            name="specialnost",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="kadry",
                to="object.specialnost",
                verbose_name="Специальность",
            ),
        ),
    ]
