# Generated by Django 5.0 on 2025-06-25 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("object", "0002_remove_resursypoobjektu_tip"),
    ]

    operations = [
        migrations.CreateModel(
            name="FakticheskijResursPoObjektu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resurs_po_objektu",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="object.resursypoobjektu",
                        verbose_name="Ресурс по объекту",
                    ),
                ),
            ],
            options={
                "verbose_name": "Фактический ресурс по объекту",
                "verbose_name_plural": "Фактические ресурсы по объектам",
                "db_table": "fakticheskij_resurs_po_objektu",
            },
        ),
        migrations.CreateModel(
            name="RaskhodResursa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(verbose_name="Дата")),
                (
                    "izraskhodovano",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Израсходовано"
                    ),
                ),
                (
                    "fakticheskij_resurs",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="object.fakticheskijresurspoobjektu",
                        verbose_name="Фактический ресурс",
                    ),
                ),
            ],
            options={
                "verbose_name": "Расход ресурса",
                "verbose_name_plural": "Расходы ресурсов",
                "db_table": "raskhod_resursa",
            },
        ),
    ]
