# Generated by Django 5.0 on 2025-06-26 09:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("object", "0003_fakticheskijresurspoobjektu_raskhodresursa"),
    ]

    operations = [
        migrations.AddField(
            model_name="resursypoobjektu",
            name="potracheno",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Потрачено лимитов",
            ),
        ),
    ]
