# Generated by Django 5.0 on 2025-06-26 10:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("object", "0004_resursypoobjektu_potracheno"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="raskhodresursa",
            unique_together={("fakticheskij_resurs", "data")},
        ),
    ]
