# Generated by Django 5.2.3 on 2025-07-01 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("object", "0005_alter_raskhodresursa_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="DokhodResursa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(verbose_name="Дата")),
                (
                    "dokhod",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Доход"
                    ),
                ),
                (
                    "fakticheskij_resurs",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="object.fakticheskijresurspoobjektu",
                        verbose_name="Фактический ресурс",
                    ),
                ),
            ],
            options={
                "verbose_name": "Доход ресурса",
                "verbose_name_plural": "Доходы ресурсов",
                "db_table": "dokhod_resursa",
                "unique_together": {("fakticheskij_resurs", "data")},
            },
        ),
    ]
