# Generated by Django 5.0 on 2025-07-03 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("object", "0008_add_svodnaya_table"),
        ("sotrudniki", "0002_organizaciya_sotrudnik_organizaciya"),
    ]

    operations = [
        migrations.AddField(
            model_name="objekt",
            name="organizaciya",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="objekty",
                to="sotrudniki.organizaciya",
                verbose_name="Организация",
            ),
        ),
        migrations.AlterField(
            model_name="dokhodresursa",
            name="vypolneno",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Выполнено"
            ),
        ),
    ]
