# Generated by Django 5.0 on 2025-07-05 07:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("object", "0010_kategoriyapoobjektu"),
    ]

    operations = [
        migrations.AddField(
            model_name="objekt",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активный"),
        ),
    ]
