# Generated by Django 5.0 on 2025-07-10 12:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("object", "0012_remove_kadry_specialnost_alter_objekt_otvetstvennyj_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="kategoriyaresursa",
            name="raskhod_dokhod",
            field=models.BooleanField(default=True, verbose_name="Расход-доход"),
        ),
    ]
