# Generated by Django 5.0 on 2025-07-11 11:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("object", "0013_kategoriyaresursa_raskhod_dokhod"),
        ("sotrudniki", "0041_alter_sotrudnikishablonyprotokolov_kurs"),
    ]

    operations = [
        migrations.AddField(
            model_name="objekt",
            name="sotrudniki",
            field=models.ManyToManyField(
                blank=True,
                help_text="Сотрудники, работающие на данном объекте",
                to="sotrudniki.sotrudnik",
                verbose_name="Сотрудники",
            ),
        ),
    ]
