# Generated by Django 5.0 on 2025-07-11 19:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("object", "0014_objekt_sotrudniki"),
        ("sotrudniki", "0043_specialnost_kategoriya"),
    ]

    operations = [
        migrations.AlterField(
            model_name="objekt",
            name="sotrudniki",
            field=models.ManyToManyField(
                blank=True,
                help_text="Сотрудники, работающие на данном объекте",
                related_name="objekty_work",
                to="sotrudniki.sotrudnik",
                verbose_name="Сотрудники",
            ),
        ),
    ]
