# Generated by Django 5.0 on 2025-07-13 08:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("object", "0015_alter_objekt_sotrudniki"),
    ]

    operations = [
        migrations.RunSQL(
            "DROP TABLE IF EXISTS object_kategoriyapoobjektu;",
            reverse_sql=""
        ),
    ]
