# Generated by Django 5.0 on 2025-07-13 09:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("object", "0016_auto_20250713_1149"),
    ]

    operations = [
        migrations.CreateModel(
            name="ObjectJson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nazvanie", models.CharField(max_length=255, verbose_name="Название")),
                ("json_struktura", models.JSONField(verbose_name="JSON структура")),
                (
                    "data_sozdaniya",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
            ],
            options={
                "verbose_name": "JSON объект",
                "verbose_name_plural": "JSON объекты",
                "db_table": "object_json",
            },
        ),
        migrations.DeleteModel(
            name="KategoriyaPoObjektu",
        ),
    ]
