# Generated by Django 5.0 on 2025-07-13 20:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("object", "0017_objectjson_delete_kategoriyapoobjektu"),
    ]

    operations = [
        migrations.AddField(
            model_name="kategoriyaresursa",
            name="order",
            field=models.IntegerField(default=0, verbose_name="Порядок"),
        ),
    ]
