# Generated by Django 5.0 on 2025-07-13 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("object", "0018_kategoriyaresursa_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resursypoobjektu",
            name="resurs",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="object.resurs",
                verbose_name="Ресурс",
            ),
        ),
    ]
