# Generated by Django 5.2.3 on 2025-07-14 20:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("object", "0019_alter_resursypoobjektu_resurs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kategoriyaresursa",
            name="order",
            field=models.IntegerField(default=100, verbose_name="Порядок"),
        ),
    ]
