# Generated by Django 5.0 on 2025-07-16 08:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("object", "0020_alter_kategoriyaresursa_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="objekt",
            name="chat_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="ID чата"
            ),
        ),
    ]
