# Generated by Django 5.2.3 on 2025-07-27 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("object", "0022_userprofile"),
        ("sotrudniki", "0053_add_default_podrazdelenie_to_organizacii"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="organizations",
            field=models.ManyToManyField(
                blank=True,
                related_name="users",
                to="sotrudniki.organizaciya",
                verbose_name="Организации",
            ),
        ),
    ]
