# Generated by Django 5.2.3 on 2025-07-27 12:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("object", "0023_userprofile_organizations"),
        ("sotrudniki", "0053_add_default_podrazdelenie_to_organizacii"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="objekt",
            name="organizaciya",
        ),
        migrations.AddField(
            model_name="objekt",
            name="organizacii",
            field=models.ManyToManyField(
                blank=True,
                related_name="objekty",
                to="sotrudniki.organizaciya",
                verbose_name="Организации",
            ),
        ),
    ]
