# Generated by Django 5.0 on 2025-08-03 20:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("object", "0024_remove_objekt_organizaciya_objekt_organizacii"),
    ]

    operations = [
        migrations.AddField(
            model_name="objekt",
            name="demo",
            field=models.BooleanField(default=False, verbose_name="Демо"),
        ),
    ]
