# Generated by Django 5.2.3 on 2025-08-05 23:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("object", "0002_add_demo_field_to_user"),
        ("object", "0025_objekt_demo"),
    ]

    operations = []
