# Generated by Django 5.0 on 2025-06-24 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdministrativnoBytovyeRashody",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nazvanie", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "edinica_izmereniya",
                    models.CharField(max_length=50, verbose_name="Единица измерения"),
                ),
            ],
            options={
                "verbose_name": "Административно-бытовые расходы",
                "verbose_name_plural": "Административно-бытовые расходы",
            },
        ),
        migrations.CreateModel(
            name="InstrumentMaterialy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nazvanie", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "edinica_izmereniya",
                    models.CharField(max_length=50, verbose_name="Единица измерения"),
                ),
            ],
            options={
                "verbose_name": "Инструмент и материалы",
                "verbose_name_plural": "Инструмент и материалы",
            },
        ),
        migrations.CreateModel(
            name="KadrovoeObespechenie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "naimenovanie",
                    models.CharField(max_length=255, verbose_name="Наименование"),
                ),
                (
                    "edinica_izmereniya",
                    models.CharField(max_length=50, verbose_name="Единица измерения"),
                ),
            ],
            options={
                "verbose_name": "Кадровое обеспечение",
                "verbose_name_plural": "Кадровое обеспечение",
            },
        ),
        migrations.CreateModel(
            name="MashinyMekhanizmy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nazvanie", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "edinica_izmereniya",
                    models.CharField(max_length=50, verbose_name="Единица измерения"),
                ),
            ],
            options={
                "verbose_name": "Машины и механизмы",
                "verbose_name_plural": "Машины и механизмы",
            },
        ),
        migrations.CreateModel(
            name="PodryadnyeOrganizacii",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "naimenovanie",
                    models.CharField(max_length=255, verbose_name="Наименование"),
                ),
                (
                    "edinica_izmereniya",
                    models.CharField(max_length=50, verbose_name="Единица измерения"),
                ),
            ],
            options={
                "verbose_name": "Подрядные организации",
                "verbose_name_plural": "Подрядные организации",
            },
        ),
        migrations.CreateModel(
            name="Specialnost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nazvanie",
                    models.CharField(
                        max_length=255, verbose_name="Название специальности"
                    ),
                ),
            ],
            options={
                "verbose_name": "Специальность",
                "verbose_name_plural": "Специальности",
            },
        ),
        migrations.CreateModel(
            name="SpecodezhaSiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nazvanie", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "edinica_izmereniya",
                    models.CharField(max_length=50, verbose_name="Единица измерения"),
                ),
            ],
            options={
                "verbose_name": "Спецодежда и СИЗ",
                "verbose_name_plural": "Спецодежда и СИЗ",
            },
        ),
        migrations.CreateModel(
            name="Kadry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fio", models.CharField(max_length=255, verbose_name="ФИО")),
                ("razryad", models.CharField(max_length=50, verbose_name="Разряд")),
                ("pasport", models.CharField(max_length=100, verbose_name="Паспорт")),
                ("telefon", models.CharField(max_length=20, verbose_name="Телефон")),
                (
                    "specialnost",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kadry",
                        to="object.specialnost",
                        verbose_name="Специальность",
                    ),
                ),
            ],
            options={
                "verbose_name": "Кадр",
                "verbose_name_plural": "Кадры",
            },
        ),
    ]
