# Generated by Django 5.0 on 2025-06-25 12:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("object", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resursypoobjektu",
            name="tip",
        ),
    ]
