# Generated by Django 5.2.3 on 2025-07-04 07:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("telegrambot", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TemporaryDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField(verbose_name="Содержание документа")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="temp_documents",
                        to="telegrambot.telegramuser",
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Временный документ",
                "verbose_name_plural": "Временные документы",
                "ordering": ["-created_at"],
            },
        ),
    ]
