# Generated by Django 5.2.3 on 2025-07-16 09:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("telegrambot", "0002_temporarydocument"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chat_id", models.CharField(max_length=255, verbose_name="ID чата")),
                ("message_text", models.TextField(verbose_name="Текст сообщения")),
                (
                    "from_user",
                    models.CharField(max_length=255, verbose_name="От пользователя"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
            ],
            options={
                "verbose_name": "Сообщение чата",
                "verbose_name_plural": "Сообщения чатов",
                "ordering": ["-created_at"],
            },
        ),
    ]
