# Generated by Django 5.0 on 2025-07-17 07:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("telegrambot", "0003_chatmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="forward_from",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Информация о пересланном сообщении"
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="message_id",
            field=models.BigIntegerField(
                blank=True, null=True, verbose_name="ID сообщения"
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="reply_to_message_id",
            field=models.BigIntegerField(
                blank=True, null=True, verbose_name="ID сообщения, на которое отвечают"
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["chat_id"], name="telegrambot_chat_id_4dd5be_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["message_id"], name="telegrambot_message_9e7365_idx"
            ),
        ),
    ]
