# Generated by Django 5.2.3 on 2025-07-18 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegrambot', '0005_processedupdate'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='processedupdate',
            new_name='telegrambot_update__4ca35a_idx',
            old_name='telegrambot_update_i_e0d1a8_idx',
        ),
        migrations.RenameIndex(
            model_name='processedupdate',
            new_name='telegrambot_process_7c39f4_idx',
            old_name='telegrambot_process_9c0e9c_idx',
        ),
    ]
