# Generated by Django 5.0 on 2025-07-03 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sotrudniki", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organizaciya",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nazvanie", models.CharField(max_length=300, verbose_name="Название")),
                (
                    "inn",
                    models.CharField(max_length=12, unique=True, verbose_name="ИНН"),
                ),
            ],
            options={
                "verbose_name": "Организация",
                "verbose_name_plural": "Организации",
            },
        ),
        migrations.AddField(
            model_name="sotrudnik",
            name="organizaciya",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sotrudniki",
                to="sotrudniki.organizaciya",
                verbose_name="Организация",
            ),
        ),
    ]
