# Generated by Django 5.2.3 on 2025-07-04 08:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sotrudniki", "0002_organizaciya_sotrudnik_organizaciya"),
    ]

    operations = [
        migrations.AddField(
            model_name="instrukciikartochki",
            name="file_path",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="Путь к файлу"
            ),
        ),
    ]
