# Generated by Django 5.0 on 2025-07-04 12:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sotrudniki", "0003_instrukciikartochki_file_path"),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrukciikartochki',
            name='tekst_kartochki',
        ),
        migrations.AddField(
            model_name='instrukciikartochki',
            name='ssylka_na_dokument',
            field=models.URLField(max_length=500, null=True, blank=True, verbose_name='Ссылка на документ'),
        ),
    ]
