# Generated by Django 5.0 on 2025-07-05 07:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sotrudniki", "0004_auto_20250704_1529"),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrukciikartochki',
            name='file_path',
        ),
        migrations.RenameField(
            model_name='instrukciikartochki',
            old_name='ssylka_na_dokument',
            new_name='shablon_instrukcii',
        ),
    ]
