# Generated by Django 5.0 on 2025-07-05 07:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sotrudniki", "0005_auto_20250705_1008"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShablonDolzhnostnojInstrukcii",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите название должностной инструкции",
                        max_length=255,
                        verbose_name="Название шаблона",
                    ),
                ),
                (
                    "html_file",
                    models.FileField(
                        help_text="Загрузите HTML файл с шаблоном инструкции",
                        upload_to="instruction_templates/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["html"]
                            )
                        ],
                        verbose_name="HTML файл инструкции",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Шаблон должностной инструкции",
                "verbose_name_plural": "Шаблоны должностных инструкций",
                "ordering": ["name"],
            },
        ),
        migrations.AlterField(
            model_name="instrukciikartochki",
            name="shablon_instrukcii",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="Шаблон инструкции"
            ),
        ),
    ]
