# Generated by Django 5.0 on 2025-07-05 07:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sotrudniki", "0006_shablondolzhnostnojinstrukcii_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizaciya",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активная"),
        ),
    ]
