# Generated by Django 5.0 on 2025-07-05 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sotrudniki", "0007_organizaciya_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="podrazdelenie",
            name="organizaciya",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="podrazdeleniya",
                to="sotrudniki.organizaciya",
                verbose_name="Организация",
            ),
        ),
    ]
