# Generated by Django 5.0 on 2025-07-05 17:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sotrudniki", "0008_podrazdelenie_organizaciya"),
    ]

    operations = [
        migrations.AddField(
            model_name="specialnost",
            name="html_file",
            field=models.FileField(
                blank=True,
                help_text="Загрузите HTML файл с шаблоном инструкции",
                null=True,
                upload_to="instruction_templates/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["html"]
                    )
                ],
                verbose_name="HTML файл инструкции",
            ),
        ),
    ]
