# Generated by Django 5.0 on 2025-07-05 19:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sotrudniki", "0009_specialnost_html_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShablonyDokumentovPoSpecialnosti",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dolzhnostnaya_instrukciya",
                    models.FileField(
                        blank=True,
                        help_text="Загрузите HTML файл с шаблоном должностной инструкции",
                        null=True,
                        upload_to="document_templates/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["html"]
                            )
                        ],
                        verbose_name="HTML файл должностной инструкции",
                    ),
                ),
                (
                    "lichnaya_kartochka_rabotnika",
                    models.FileField(
                        blank=True,
                        help_text="Загрузите HTML файл с шаблоном личной карточки работника",
                        null=True,
                        upload_to="document_templates/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["html"]
                            )
                        ],
                        verbose_name="HTML файл личной карточки работника",
                    ),
                ),
                (
                    "lichnaya_kartochka_siz",
                    models.FileField(
                        blank=True,
                        help_text="Загрузите HTML файл с шаблоном личной карточки учета выдачи СИЗ",
                        null=True,
                        upload_to="document_templates/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["html"]
                            )
                        ],
                        verbose_name="HTML файл личной карточки учета выдачи СИЗ",
                    ),
                ),
                (
                    "karta_ocenki_riskov",
                    models.FileField(
                        blank=True,
                        help_text="Загрузите HTML файл с шаблоном карты оценки проф. рисков",
                        null=True,
                        upload_to="document_templates/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["html"]
                            )
                        ],
                        verbose_name="HTML файл карты оценки проф. рисков",
                    ),
                ),
                (
                    "specialnost",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shablony_dokumentov",
                        to="sotrudniki.specialnost",
                        verbose_name="Специальность",
                    ),
                ),
            ],
            options={
                "verbose_name": "Шаблоны документов по специальности",
                "verbose_name_plural": "Шаблоны документов по специальностям",
            },
        ),
    ]
