# Generated by Django 5.0 on 2025-07-05 19:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sotrudniki", "0010_shablonydokumentovpospecialnosti"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="specialnost",
            name="html_file",
        ),
    ]
