# Generated by Django 5.0 on 2025-07-05 20:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sotrudniki", "0011_remove_specialnost_html_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="sotrudnik",
            name="pol",
            field=models.CharField(
                blank=True,
                choices=[("мужской", "Мужской"), ("женский", "Женский")],
                max_length=10,
                null=True,
                verbose_name="Пол",
            ),
        ),
        migrations.AddField(
            model_name="sotrudnik",
            name="razmer_golovnogo_ubora",
            field=models.CharField(
                default="55", max_length=5, verbose_name="Размер головного убора"
            ),
        ),
        migrations.AddField(
            model_name="sotrudnik",
            name="razmer_obuvi",
            field=models.CharField(
                default="43", max_length=5, verbose_name="Размер обуви"
            ),
        ),
        migrations.AddField(
            model_name="sotrudnik",
            name="razmer_odezhdy",
            field=models.CharField(
                default="50-52", max_length=10, verbose_name="Размер одежды"
            ),
        ),
    ]
