# Generated by Django 5.0 on 2025-07-06 09:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sotrudniki", "0012_sotrudnik_pol_sotrudnik_razmer_golovnogo_ubora_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shablonydokumentovpospecialnosti",
            name="instrukciya_po_ohrane_truda",
            field=models.FileField(
                blank=True,
                default="media/document_templates/instrukciya_po_ohrane_truda_template.html",
                help_text="Загрузите HTML файл с шаблоном инструкции по охране труда",
                null=True,
                upload_to="document_templates/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["html"]
                    )
                ],
                verbose_name="HTML файл инструкции по охране труда",
            ),
        ),
    ]
