# Generated by Django 5.0 on 2025-07-06 09:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "sotrudniki",
            "0014_alter_shablonydokumentovpospecialnosti_instrukciya_po_ohrane_truda",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="shablonydokumentovpospecialnosti",
            name="instrukciya_po_ohrane_truda",
            field=models.FileField(
                blank=True,
                default="document_templates/instrukciya_po_ohrane_truda_template.html",
                help_text="Загрузите HTML файл с шаблоном инструкции по охране труда",
                null=True,
                upload_to="document_templates/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["html"]
                    )
                ],
                verbose_name="HTML файл инструкции по охране труда",
            ),
        ),
    ]
