# Generated by Django 5.0 on 2025-07-06 12:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "sotrudniki",
            "0015_alter_shablonydokumentovpospecialnosti_instrukciya_po_ohrane_truda",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="protokolyobucheniya",
            options={
                "verbose_name": "Сотрудники шаблоны протоколов",
                "verbose_name_plural": "Сотрудники шаблоны протоколов",
            },
        ),
    ]
