# Generated by Django 5.0 on 2025-07-07 06:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sotrudniki", "0016_alter_protokolyobucheniya_options"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ShablonDolzhnostnojInstrukcii",
        ),
        migrations.DeleteModel(
            name="VidyDokumentov",
        ),
    ]
