# Generated by Django 5.0 on 2025-07-07 06:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sotrudniki", "0017_delete_shablondolzhnostnojinstrukcii_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SotrudnikiShablonyProtokolov",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "html_file",
                    models.FileField(
                        help_text="Загрузите HTML файл с шаблоном протокола",
                        upload_to="instruction_templates/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["html"]
                            )
                        ],
                        verbose_name="HTML файл протокола",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сотрудники шаблоны протоколов",
                "verbose_name_plural": "Сотрудники шаблоны протоколов",
            },
        ),
    ]
