# Generated by Django 5.0 on 2025-07-07 06:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sotrudniki", "0018_sotrudnikishablonyprotokolov"),
    ]

    operations = [
        migrations.AddField(
            model_name='sotrudnikishablonyprotokolov',
            name='nomer_programmy',
            field=models.CharField(default='', max_length=50, verbose_name='№ программы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sotrudnikishablonyprotokolov',
            name='kurs',
            field=models.CharField(default='', max_length=200, verbose_name='Курс'),
            preserve_default=False,
        ),
    ]
