# Generated by Django 5.0 on 2025-07-07 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("sotrudniki", "0019_auto_20250707_0952"),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protokolyobucheniya',
            name='nomer_programmy',
        ),
        migrations.RemoveField(
            model_name='protokolyobucheniya',
            name='nazvanie_kursa',
        ),
        migrations.RemoveField(
            model_name='protokolyobucheniya',
            name='tekst_protokola',
        ),
        migrations.RemoveField(
            model_name='protokolyobucheniya',
            name='data_dopuska',
        ),
        migrations.AddField(
            model_name='protokolyobucheniya',
            name='shablon_protokola',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to='sotrudniki.sotrudnikishablonyprotokolov',
                verbose_name='Шаблон протокола'
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='protokolyobucheniya',
            name='data_protokola_dopuska',
            field=models.DateField(
                default='2025-01-01',
                verbose_name='Дата протокола/приказа-допуска'
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='protokolyobucheniya',
            name='data_dopuska_k_rabote',
            field=models.DateField(
                default='2025-01-01',
                verbose_name='Дата допуска к работе'
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='protokolyobucheniya',
            name='registracionnyy_nomer',
            field=models.CharField(max_length=50, verbose_name='Рег №'),
        ),
        migrations.AlterField(
            model_name='protokolyobucheniya',
            name='raspechatn',
            field=models.BooleanField(default=False, verbose_name='Распеч'),
        ),
        migrations.AlterModelOptions(
            name='protokolyobucheniya',
            options={'verbose_name': 'Протокол обучения', 'verbose_name_plural': 'Протоколы обучения'},
        ),
    ]
