# Generated by Django 5.0 on 2025-07-07 07:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sotrudniki", "0020_auto_20250707_1022"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProtokolyObucheniya",
        ),
    ]
