# Generated by Django 5.0 on 2025-07-07 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sotrudniki", "0021_delete_protokolyobucheniya"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProtokolyObucheniya",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_prikaza", models.DateField(verbose_name="Дата приказа")),
                (
                    "data_protokola_dopuska",
                    models.DateField(verbose_name="Дата протокола/приказа-допуска"),
                ),
                (
                    "data_dopuska_k_rabote",
                    models.DateField(verbose_name="Дата допуска к работе"),
                ),
                (
                    "data_ocherednoy_proverki",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата очередной проверки"
                    ),
                ),
                (
                    "registracionnyy_nomer",
                    models.CharField(max_length=50, verbose_name="Рег №"),
                ),
                (
                    "raspechatn",
                    models.BooleanField(default=False, verbose_name="Распеч"),
                ),
                (
                    "dokumenty_sotrudnika",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sotrudniki.dokumentysotrudnika",
                        verbose_name="Документы сотрудника",
                    ),
                ),
                (
                    "shablon_protokola",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sotrudniki.sotrudnikishablonyprotokolov",
                        verbose_name="Шаблон протокола",
                    ),
                ),
            ],
            options={
                "verbose_name": "Протокол обучения",
                "verbose_name_plural": "Протоколы обучения",
            },
        ),
    ]
