# Generated by Django 5.0 on 2025-07-07 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("sotrudniki", "0022_protokolyobucheniya"),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protokolyobucheniya',
            name='dokumenty_sotrudnika',
        ),
        migrations.AddField(
            model_name='protokolyobucheniya',
            name='sotrudnik',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='protokoly_obucheniya',
                to='sotrudniki.sotrudnik',
                verbose_name='Сотрудник'
            ),
            preserve_default=False,
        ),
    ]
