# Generated by Django 5.2.3 on 2025-07-07 19:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sotrudniki", "0023_auto_20250707_1341"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="instruktazhi",
            name="dokumenty_sotrudnika",
        ),
        migrations.RemoveField(
            model_name="instrukciikartochki",
            name="dokumenty_sotrudnika",
        ),
        # migrations.DeleteModel(
        #     name="DokumentySotrudnika",
        # ),
    ]
