# Generated by Django 5.0 on 2025-07-07 21:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sotrudniki", "0024_remove_instruktazhi_dokumenty_sotrudnika_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name='organizaciya',
            name='ogrn',
            field=models.CharField(max_length=15, verbose_name='ОГРН', null=True, blank=True),
        ),
        migrations.AddField(
            model_name='organizaciya',
            name='adres',
            field=models.TextField(verbose_name='Адрес', null=True, blank=True),
        ),
    ]
