# Generated by Django 5.0 on 2025-07-07 22:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sotrudniki", "0025_auto_20250708_0031"),
    ]

    operations = [
        migrations.AlterField(
            model_name='protokolyobucheniya',
            name='shablon_protokola',
            field=models.ForeignKey(
                on_delete=models.CASCADE,
                to='sotrudniki.sotrudnikishablonyprotokolov',
                verbose_name='Шаблон протокола'
            ),
        ),
    ]
