# Generated by Django 5.2.3 on 2025-07-08 06:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sotrudniki", "0026_auto_20250708_0110"),
    ]

    operations = []
