# Generated by Django 5.0 on 2025-07-08 06:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sotrudniki", "0027_auto_20250708_0956"),
    ]

    operations = [
        migrations.AddField(
            model_name='sotrudnikishablonyprotokolov',
            name='specialnost',
            field=models.ManyToManyField(
                to='sotrudniki.specialnost',
                verbose_name='Специальности',
                help_text='Выберите специальности, для которых подходит этот шаблон',
                blank=True
            ),
        ),
    ]
