# Generated by Django 5.2.3 on 2025-07-08 08:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sotrudniki", "0028_auto_20250708_0956"),
    ]

    operations = []
