# Generated by Django 5.0 on 2025-07-08 08:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sotrudniki", "0029_auto_20250708_1100"),
    ]

    operations = []
