# Generated by Django 5.2.3 on 2025-07-08 08:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sotrudniki", "0030_auto_20250708_1102"),
    ]

    operations = []
