# Generated by Django 5.0 on 2025-07-08 08:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sotrudniki", "0031_auto_20250708_1104"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dokumentysotrudnika",
            name="sotrudnik",
        ),
        migrations.DeleteModel(
            name="InstrukciiKartochki",
        ),
        migrations.DeleteModel(
            name="Instruktazhi",
        ),
        migrations.DeleteModel(
            name="DokumentySotrudnika",
        ),
    ]
