# Generated by Django 5.0 on 2025-07-08 08:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sotrudniki", "0032_remove_dokumentysotrudnika_sotrudnik_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Instruktazhi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tip_instruktazha",
                    models.CharField(
                        choices=[
                            ("вводный", "Вводный"),
                            ("первичный", "Первичный"),
                            ("повторный", "Повторный"),
                            ("внеплановый", "Внеплановый"),
                            ("целевой", "Целевой"),
                        ],
                        max_length=20,
                        verbose_name="Тип инструктажа",
                    ),
                ),
                (
                    "data_provedeniya",
                    models.DateField(verbose_name="Дата проведения инструктажа"),
                ),
                (
                    "html_file",
                    models.FileField(
                        default="instruction_templates/instruktag.html",
                        upload_to="instruction_templates/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["html"]
                            )
                        ],
                        verbose_name="HTML файл инструктажа",
                    ),
                ),
                (
                    "instruktor",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sotrudniki.sotrudnik",
                        verbose_name="Инструктор",
                    ),
                ),
                (
                    "specialnost",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sotrudniki.specialnost",
                        verbose_name="Специальность",
                    ),
                ),
            ],
            options={
                "verbose_name": "Инструктаж",
                "verbose_name_plural": "Инструктажи",
            },
        ),
    ]
