# Generated by Django 5.0 on 2025-07-08 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sotrudniki", "0033_instruktazhi"),
    ]

    operations = [
        migrations.AddField(
            model_name="instruktazhi",
            name="sotrudnik",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="instruktazhi",
                to="sotrudniki.sotrudnik",
                verbose_name="Сотрудник",
            ),
        ),
        migrations.AlterField(
            model_name="instruktazhi",
            name="instruktor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="instruktazhi_kak_instruktor",
                to="sotrudniki.sotrudnik",
                verbose_name="Инструктор",
            ),
        ),
    ]
