# Generated by Django 5.0 on 2025-07-08 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sotrudniki", "0034_instruktazhi_sotrudnik_alter_instruktazhi_instruktor"),
    ]

    operations = [
        migrations.CreateModel(
            name="DokumentySotrudnika",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tip_dokumenta",
                    models.CharField(
                        choices=[
                            ("dolzhnostnaya", "Должностная инструкция"),
                            ("kartochka", "Личная карточка работника"),
                            ("siz", "Личная карточка СИЗ"),
                            ("riski", "Карта оценки рисков"),
                        ],
                        max_length=50,
                        verbose_name="Тип документа",
                    ),
                ),
                ("sozdano", models.BooleanField(default=True, verbose_name="Создано")),
                (
                    "data_sozdaniya",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "sotrudnik",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dokumenty",
                        to="sotrudniki.sotrudnik",
                        verbose_name="Сотрудник",
                    ),
                ),
            ],
            options={
                "verbose_name": "Документ сотрудника",
                "verbose_name_plural": "Документы сотрудников",
                "unique_together": {("sotrudnik", "tip_dokumenta")},
            },
        ),
    ]
