# Generated by Django 5.2.3 on 2025-07-08 13:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sotrudniki", "0036_shablonyinstruktazhej"),
    ]

    operations = []
