# Generated by Django 5.0 on 2025-07-08 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("sotrudniki", "0037_auto_20250708_1605"),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instruktazhi',
            name='specialnost',
        ),
        migrations.RemoveField(
            model_name='instruktazhi',
            name='tip_instruktazha',
        ),
        migrations.RemoveField(
            model_name='instruktazhi',
            name='html_file',
        ),
        migrations.AddField(
            model_name='instruktazhi',
            name='instruktazh',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='sotrudniki.shablonyinstruktazhej',
                verbose_name='Инструктаж',
                default=1
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='instruktazhi',
            name='sotrudnik',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='instruktazhi',
                to='sotrudniki.sotrudnik',
                verbose_name='Сотрудник'
            ),
        ),
    ]
