# Generated by Django 5.0 on 2025-07-09 08:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sotrudniki", "0038_auto_20250708_1613"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dokumentysotrudnika",
            options={
                "verbose_name": "Документ сотрудника",
                "verbose_name_plural": "Документы",
            },
        ),
        migrations.AlterModelOptions(
            name="protokolyobucheniya",
            options={
                "verbose_name": "Протокол обучения",
                "verbose_name_plural": "Протоколы",
            },
        ),
        migrations.AlterModelOptions(
            name="shablonydokumentovpospecialnosti",
            options={
                "verbose_name": "Документы по специальностям",
                "verbose_name_plural": "Документы - шаблоны",
            },
        ),
        migrations.AlterModelOptions(
            name="shablonyinstruktazhej",
            options={
                "verbose_name": "Инструктаж - шаблон",
                "verbose_name_plural": "Инструктажи - шаблоны",
            },
        ),
        migrations.AlterModelOptions(
            name="sotrudnikishablonyprotokolov",
            options={
                "verbose_name": "Протоколы обучения- шаблоны",
                "verbose_name_plural": "Протоколы - шаблоны ",
            },
        ),
        migrations.AlterField(
            model_name="instruktazhi",
            name="data_provedeniya",
            field=models.DateField(verbose_name="Дата проведения"),
        ),
    ]
