# Generated by Django 5.0 on 2025-07-09 08:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sotrudniki", "0039_alter_dokumentysotrudnika_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sotrudnikishablonyprotokolov",
            name="nomer_programmy",
        ),
        migrations.AddField(
            model_name="protokolyobucheniya",
            name="nomer_programmy",
            field=models.CharField(
                default="2025/AA.00-0000", max_length=50, verbose_name="№ программы"
            ),
        ),
    ]
