# Generated by Django 5.0 on 2025-07-09 08:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "sotrudniki",
            "0040_remove_sotrudnikishablonyprotokolov_nomer_programmy_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="sotrudnikishablonyprotokolov",
            name="kurs",
            field=models.CharField(max_length=500, verbose_name="Курс"),
        ),
    ]
