# Generated by Django 5.0 on 2025-07-11 11:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("object", "0014_objekt_sotrudniki"),
        ("sotrudniki", "0041_alter_sotrudnikishablonyprotokolov_kurs"),
    ]

    operations = [
        migrations.AddField(
            model_name="sotrudnik",
            name="objekty",
            field=models.ManyToManyField(
                blank=True,
                help_text="Объекты, на которых работает сотрудник",
                to="object.objekt",
                verbose_name="Объекты",
            ),
        ),
    ]
