# Generated by Django 5.0 on 2025-07-11 13:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sotrudniki", "0042_sotrudnik_objekty"),
    ]

    operations = [
        migrations.AddField(
            model_name="specialnost",
            name="kategoriya",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Категория"
            ),
        ),
    ]
