# Generated by Django 5.0 on 2025-07-14 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("object", "0020_alter_kategoriyaresursa_order"),
        ("sotrudniki", "0043_specialnost_kategoriya"),
    ]

    operations = [
        migrations.CreateModel(
            name="SotrudnikiZarplaty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(verbose_name="Дата")),
                (
                    "kolichestvo_chasov",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Количество часов"
                    ),
                ),
                (
                    "kpi",
                    models.DecimalField(
                        decimal_places=2, default=1.0, max_digits=5, verbose_name="KPI"
                    ),
                ),
                (
                    "objekt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="object.objekt",
                        verbose_name="Объект",
                    ),
                ),
                (
                    "sotrudnik",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sotrudniki.sotrudnik",
                        verbose_name="Сотрудник",
                    ),
                ),
            ],
            options={
                "verbose_name": "Зарплата сотрудника",
                "verbose_name_plural": "Зарплаты сотрудников",
                "db_table": "sotrudniki_zarplaty",
                "unique_together": {("sotrudnik", "objekt", "data")},
            },
        ),
    ]
