# Generated by Django 5.0 on 2025-07-15 07:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sotrudniki", "0044_sotrudnikizarplaty"),
    ]

    operations = [
        migrations.AddField(
            model_name="sotrudnikizarplaty",
            name="vydano",
            field=models.BooleanField(default=False, verbose_name="Выдано"),
        ),
    ]
