# Generated by Django 5.0 on 2025-07-15 11:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sotrudniki", "0045_sotrudnikizarplaty_vydano"),
    ]

    operations = [
        migrations.AddField(
            model_name="sotrudnik",
            name="bazovoe_obuchenie",
            field=models.BooleanField(default=True, verbose_name="Базовое обучение"),
        ),
        migrations.AddField(
            model_name="sotrudnik",
            name="dopusk_k_rabote",
            field=models.BooleanField(default=True, verbose_name="Допуск к работе"),
        ),
        migrations.AddField(
            model_name="sotrudnik",
            name="med_osvidetelstvovanie",
            field=models.BooleanField(
                default=True, verbose_name="Мед.освидетельствование"
            ),
        ),
        migrations.AddField(
            model_name="sotrudnik",
            name="obuchenie_na_predpriyatii",
            field=models.BooleanField(
                default=True, verbose_name="Обучение на предприятии"
            ),
        ),
    ]
