# Generated by Django 5.0 on 2025-07-15 11:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sotrudniki", "0046_sotrudnik_bazovoe_obuchenie_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sotrudnik",
            name="stazhirovka",
            field=models.BooleanField(default=True, verbose_name="Стажировка"),
        ),
    ]
