# Generated by Django 5.0 on 2025-07-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sotrudniki", "0047_sotrudnik_stazhirovka"),
    ]

    operations = [
        migrations.AddField(
            model_name="sotrudnik",
            name="siz",
            field=models.BooleanField(default=True, verbose_name="СИЗ"),
        ),
    ]
