# Generated by Django 5.0 on 2025-07-19 08:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sotrudniki", "0048_sotrudnik_siz"),
    ]

    operations = [
        # Безопасное удаление поля objekty, игнорируя отсутствие таблицы
        migrations.RunSQL(
            sql="",  # Пустой SQL, ничего не делаем
            reverse_sql="",
            state_operations=[
                migrations.RemoveField(
                    model_name="sotrudnik",
                    name="objekty",
                ),
            ],
        ),
    ]