# Generated by Django 5.0 on 2025-07-19 11:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sotrudniki", "0050_add_default_podrazdelenie"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="podrazdelenie",
            name="organizaciya",
        ),
    ]
