# Generated by Django 5.0 on 2025-07-19 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sotrudniki", "0051_remove_organizaciya_from_podrazdelenie"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizaciyaPodrazdelenie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="По умолчанию"),
                ),
                (
                    "organizaciya",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sotrudniki.organizaciya",
                        verbose_name="Организация",
                    ),
                ),
                (
                    "podrazdelenie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sotrudniki.podrazdelenie",
                        verbose_name="Подразделение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Подразделение организации",
                "verbose_name_plural": "Подразделения организаций",
                "unique_together": {("organizaciya", "podrazdelenie")},
            },
        ),
        migrations.AddField(
            model_name="organizaciya",
            name="podrazdeleniya",
            field=models.ManyToManyField(
                blank=True,
                related_name="organizacii",
                through="sotrudniki.OrganizaciyaPodrazdelenie",
                to="sotrudniki.podrazdelenie",
                verbose_name="Подразделения",
            ),
        ),
    ]
