# Generated by Django 5.0 on 2025-08-05 12:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sotrudniki", "0053_add_default_podrazdelenie_to_organizacii"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizaciya",
            name="demo",
            field=models.BooleanField(default=False, verbose_name="Демо"),
        ),
    ]
