# Generated by Django 5.2.3 on 2025-07-27 08:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cams", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="camera",
            name="ip_address",
            field=models.CharField(max_length=255, verbose_name="url"),
        ),
    ]
