# Generated by Django 5.2.3 on 2025-07-27 08:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cams", "0002_alter_camera_ip_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="camera",
            name="location",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Местоположение"
            ),
        ),
    ]
