# Generated by Django 5.2.3 on 2025-07-27 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cams", "0003_alter_camera_location"),
        ("object", "0021_objekt_chat_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="camera",
            name="objekt",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cameras",
                to="object.objekt",
                verbose_name="Объект",
            ),
        ),
    ]
