# Generated by Django 5.2.3 on 2025-07-27 08:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cams", "0004_camera_objekt"),
    ]

    operations = [
        migrations.RenameField(
            model_name="camera",
            old_name="ip_address",
            new_name="url",
        ),
    ]
