# Generated by Django 5.0 on 2025-07-31 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cams", "0005_rename_ip_address_camera_url"),
        ("object", "0024_remove_objekt_organizaciya_objekt_organizacii"),
    ]

    operations = [
        migrations.AlterField(
            model_name="camera",
            name="objekt",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cameras",
                to="object.objekt",
                verbose_name="Объект",
            ),
        ),
    ]
