# Generated by Django 5.0 on 2025-07-12 06:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai", "0002_chatsession_chatmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to="documents_ai/", verbose_name="Файл"
            ),
        ),
    ]
