# Generated by Django 5.0 on 2025-07-12 08:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai", "0003_chatmessage_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIPrompt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nazvanie", models.CharField(max_length=200, verbose_name="Название")),
                ("zapros", models.TextField(verbose_name="Запрос")),
                (
                    "struktura_otveta",
                    models.JSONField(
                        help_text="JSON структура ожидаемого ответа",
                        verbose_name="Структура ответа",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
            ],
            options={
                "verbose_name": "AI Промпт",
                "verbose_name_plural": "AI Промпты",
                "ordering": ["nazvanie"],
            },
        ),
    ]
